### ISSUE TITLE
not able to configure

### ISSUE THREAD

**Issue by amanvars** [UbiCastTeam/gst-qroverlay#2]
Hi,
Please let me know the steps to configure the project, as some of the files regarding it are missing.
Kindly attach those files also.

Thanks,
Aman

**Comment by fthiery** [comment]
I don't see what is missing, did you do the expected ?

```
$ git clone git@github.com:UbiCastTeam/gst-qroverlay.git
$ ./autogen.sh
...
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands

Now type 'make' to compile this module.
$ make
```

**Comment by amanvars** [comment]
I did run the first command but getting following issue:
**Cloning into 'gst-qroverlay'...
git@ssh.github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.**

Then i tried with following command:
_git clone https://github.com/UbiCastTeam/gst-qroverlay.git_

It ran successfully but after it, I am not able to run second command :  ./autogen.sh
error:

./autogen.sh: 6: ./autogen.sh: autoreconf: not found
autogen.sh failed

**Comment by sschoorens** [comment]
```
git clone https://github.com/UbiCastTeam/gst-qroverlay.git
cd gst-qroverlay
./autogen.sh
```

**Comment by nikaro** [comment]
@amanvars did you do: `apt install libqrencode-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev`?

**Comment by amanvars** [comment]
Thank you all of u. It is installed now.
After running following command:
gst-launch-1.0 videotestsrc pattern=2 ! "video/x-raw, format=(string)I420, width=(int)320, height=(int)240, framerate=(fraction)30/1" ! qroverlay name=testoverlay x=50 qrcode-error-correction=3 extra-data-span-buffers=1 extra-data-interval-buffers=30 extra-data-name=mydata extra-data-array="240,480,720,960,1200,1440,1680,1920" pixel-size=2 ! videoconvert ! xvimagesink

Error:
Failed to start pipeline (gst_parse_error: no element "qroverlay" (1)), exiting with error


Also, kindly please help me in running the project along with your QrLipSync project.

thanks in advance

**Comment by sschoorens** [comment]
I've update the readme file for the full installation and plugin test
if you have done `sudo make install` 
please try
`GST_PLUGIN_PATH="/usr/local/lib/gstreamer-1.0/" gst-launch-1.0 videotestsrc pattern=2 ! "video/x-raw, format=(string)I420, width=(int)320, height=(int)240, framerate=(fraction)30/1" ! qroverlay name=testoverlay x=50 qrcode-error-correction=3 extra-data-span-buffers=1 extra-data-interval-buffers=30 extra-data-name=mydata extra-data-array="240,480,720,960,1200,1440,1680,1920" pixel-size=2 ! videoconvert ! xvimagesink`

this link `/usr/local/lib/gstreamer-1.0/` could be different on your system please find where the file `libgstqroverlay.so` is installed

**Comment by amanvars** [comment]
> libgstqroverlay.so

Now getting this error:
WARNING: erroneous pipeline: no element "xvimagesink"

Below is the log after _sudo make install_  
Making install in src
make[1]: Entering directory '/home/aman/Desktop/gst-qroverlay/src'
make[2]: Entering directory '/home/aman/Desktop/gst-qroverlay/src'
make[2]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/usr/local/lib/gstreamer-1.0'
 /bin/bash ../libtool   --mode=install /usr/bin/install -c   libgstqroverlay.la '/usr/local/lib/gstreamer-1.0'
libtool: install: /usr/bin/install -c .libs/libgstqroverlay.so /usr/local/lib/gstreamer-1.0/libgstqroverlay.so
libtool: install: /usr/bin/install -c .libs/libgstqroverlay.lai /usr/local/lib/gstreamer-1.0/libgstqroverlay.la
libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/sbin" ldconfig -n /usr/local/lib/gstreamer-1.0
----------------------------------------------------------------------
Libraries have been installed in:
   /usr/local/lib/gstreamer-1.0

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
make[2]: Leaving directory '/home/aman/Desktop/gst-qroverlay/src'
make[1]: Leaving directory '/home/aman/Desktop/gst-qroverlay/src'
Making install in tests
make[1]: Entering directory '/home/aman/Desktop/gst-qroverlay/tests'
make[2]: Entering directory '/home/aman/Desktop/gst-qroverlay/tests'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/home/aman/Desktop/gst-qroverlay/tests'
make[1]: Leaving directory '/home/aman/Desktop/gst-qroverlay/tests'
make[1]: Entering directory '/home/aman/Desktop/gst-qroverlay'
make[2]: Entering directory '/home/aman/Desktop/gst-qroverlay'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/home/aman/Desktop/gst-qroverlay'
make[1]: Leaving directory '/home/aman/Desktop/gst-qroverlay'



But i am not able to find the file _**libgstqroverlay.so**_

Kindly guide me.

Thanks in advance.

**Comment by fthiery** [comment]
Your environment is obviously lacking the required dependencies. You don't need to generate the video to use this, just download a pre-rendered file here:

https://drive.google.com/uc?id=1fyvn7-xKuPcDWNoair28FZCuUnwpAoZF&export=download

**Comment by sschoorens** [comment]
`libgstqroverlay.so` has been installed in `/usr/local/lib/gstreamer-1.0` so everything is ok

to test the cmd line you have to install deps of gstreamer

`sudo  apt install gstreamer1.0-plugins-base`

**Comment by fthiery** [comment]
Take a look at https://github.com/UbiCastTeam/qr-lipsync/blob/master/Dockerfile

**Comment by aviolo** [comment]
Hello,
I updated the git readme, which should help you to install and use the plugin. If it still doesn't work, don't hesitate to come back to us.

**Comment by amanvars** [comment]
Did all the step that u have mentioned in the readme. 
Now getting following error:
WARNING: erroneous pipeline: no element "xvimagesink"


i did inspect also:
$ gst-inspect-1.0 xvimagesink
No such element or plugin 'xvimagesink'


Kindly update me.

Thanks

**Comment by sschoorens** [comment]
you probably miss this package 
`sudo apt install gstreamer1.0-plugins-base`
`xvimagesink` is inside `gst-plugins-base`

**Comment by fthiery** [comment]
You don't need this. To measure AV lipsync you must:
1) download the file i mentioned (https://drive.google.com/uc?id=1fyvn7-xKuPcDWNoair28FZCuUnwpAoZF&export=download)
2) run this file into whatever system you are trying to measure lipsync from (e.g. film a screen + audio if you test a camera), this will give you a file to analyze (e.g. file.mp4)
3) install and run https://github.com/UbiCastTeam/qr-lipsync
`qr-lipsync-detect.py file.mp4`

This project (qroverlay) is only required to _generate_ the samples, not analyze lipsync.

**Comment by amanvars** [comment]
Getting 

> You don't need this. To measure AV lipsync you must:
> 
>     1. download the file i mentioned (https://drive.google.com/uc?id=1fyvn7-xKuPcDWNoair28FZCuUnwpAoZF&export=download)
> 
>     2. run this file into whatever system you are trying to measure lipsync from (e.g. film a screen + audio if you test a camera), this will give you a file to analyze (e.g. file.mp4)
> 
>     3. install and run https://github.com/UbiCastTeam/qr-lipsync
>        `qr-lipsync-detect.py file.mp4`
> 
> 
> This project (qroverlay) is only required to _generate_ the samples, not analyze lipsync.

Getting this:
$ qr-lipsync-detect.py cam1-qrcode-blue-30.qt 
Traceback (most recent call last):
  File "/home/aman/anaconda3/bin/qr-lipsync-detect.py", line 4, in <module>
    __import__('pkg_resources').run_script('qrlipsync==1.0', 'qr-lipsync-detect.py')
  File "/home/aman/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/aman/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/qr-lipsync-detect.py' not found in metadata at '/home/aman/anaconda3/lib/python3.7/site-packages/qrlipsync-1.0-py3.7.egg-info'

**Comment by fthiery** [comment]
Take a look at the following: https://github.com/UbiCastTeam/qr-lipsync#using-with-docker

You can just, from qr-lipsync, run
```
make build_docker_img
make generate
make analyze VIDEO=cam1-qrcode-blue-30.qt
```
That way you won't have to fiddle with python/system issues.

**Comment by amanvars** [comment]
> Take a look at the following: https://github.com/UbiCastTeam/qr-lipsync#using-with-docker
> 
> You can just, from qr-lipsync, run
> 
> ```
> make build_docker_img
> make generate
> make analyze VIDEO=cam1-qrcode-blue-30.qt
> ```
> 
> That way you won't have to fiddle with python/system issues.

But I don't have a docker. I am using Anaconda in Ubuntu.
Kindly help with that configuration.

Thanks

**Comment by fthiery** [comment]
Sorry, we don't support Anaconda. Just install docker.
